grails:
  controllers:
    upload:
      maxFileSize: 524288
      maxRequestSize: 1048576
---
inertia:
  ssr:
    enabled: true
    url: 'http://localhost:13714/render'
---
csrf:
  cookie:
    domain: 'host.testcontainers.internal'
    secure: false